/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ZunctionRouteImport } from './routes/zunction'
import { Route as WorkRouteImport } from './routes/work'
import { Route as Ux_notesRouteImport } from './routes/ux_notes'
import { Route as Theses_and_experimentsRouteImport } from './routes/theses_and_experiments'
import { Route as ThesesRouteImport } from './routes/theses'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as Reimagining_indian_agricultureRouteImport } from './routes/reimagining_indian_agriculture'
import { Route as Recruiters_live_in_excelRouteImport } from './routes/recruiters_live_in_excel'
import { Route as Phone_of_friendRouteImport } from './routes/phone_of_friend'
import { Route as Phone_a_friendRouteImport } from './routes/phone_a_friend'
import { Route as Online_writingRouteImport } from './routes/online_writing'
import { Route as LifeRouteImport } from './routes/life'
import { Route as ExperimentsRouteImport } from './routes/experiments'
import { Route as Employees_skin_in_the_gameRouteImport } from './routes/employees_skin_in_the_game'
import { Route as CohortupRouteImport } from './routes/cohortup'
import { Route as CareerRouteImport } from './routes/career'
import { Route as Cafes_human_behaviourRouteImport } from './routes/cafes_human_behaviour'
import { Route as Bulk_paste_filteringRouteImport } from './routes/bulk_paste_filtering'
import { Route as Bilaspur_diariesRouteImport } from './routes/bilaspur_diaries'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const ZunctionRoute = ZunctionRouteImport.update({
  id: '/zunction',
  path: '/zunction',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkRoute = WorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => rootRouteImport,
} as any)
const Ux_notesRoute = Ux_notesRouteImport.update({
  id: '/ux_notes',
  path: '/ux_notes',
  getParentRoute: () => rootRouteImport,
} as any)
const Theses_and_experimentsRoute = Theses_and_experimentsRouteImport.update({
  id: '/theses_and_experiments',
  path: '/theses_and_experiments',
  getParentRoute: () => rootRouteImport,
} as any)
const ThesesRoute = ThesesRouteImport.update({
  id: '/theses',
  path: '/theses',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const Reimagining_indian_agricultureRoute =
  Reimagining_indian_agricultureRouteImport.update({
    id: '/reimagining_indian_agriculture',
    path: '/reimagining_indian_agriculture',
    getParentRoute: () => rootRouteImport,
  } as any)
const Recruiters_live_in_excelRoute =
  Recruiters_live_in_excelRouteImport.update({
    id: '/recruiters_live_in_excel',
    path: '/recruiters_live_in_excel',
    getParentRoute: () => rootRouteImport,
  } as any)
const Phone_of_friendRoute = Phone_of_friendRouteImport.update({
  id: '/phone_of_friend',
  path: '/phone_of_friend',
  getParentRoute: () => rootRouteImport,
} as any)
const Phone_a_friendRoute = Phone_a_friendRouteImport.update({
  id: '/phone_a_friend',
  path: '/phone_a_friend',
  getParentRoute: () => rootRouteImport,
} as any)
const Online_writingRoute = Online_writingRouteImport.update({
  id: '/online_writing',
  path: '/online_writing',
  getParentRoute: () => rootRouteImport,
} as any)
const LifeRoute = LifeRouteImport.update({
  id: '/life',
  path: '/life',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperimentsRoute = ExperimentsRouteImport.update({
  id: '/experiments',
  path: '/experiments',
  getParentRoute: () => rootRouteImport,
} as any)
const Employees_skin_in_the_gameRoute =
  Employees_skin_in_the_gameRouteImport.update({
    id: '/employees_skin_in_the_game',
    path: '/employees_skin_in_the_game',
    getParentRoute: () => rootRouteImport,
  } as any)
const CohortupRoute = CohortupRouteImport.update({
  id: '/cohortup',
  path: '/cohortup',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerRoute = CareerRouteImport.update({
  id: '/career',
  path: '/career',
  getParentRoute: () => rootRouteImport,
} as any)
const Cafes_human_behaviourRoute = Cafes_human_behaviourRouteImport.update({
  id: '/cafes_human_behaviour',
  path: '/cafes_human_behaviour',
  getParentRoute: () => rootRouteImport,
} as any)
const Bulk_paste_filteringRoute = Bulk_paste_filteringRouteImport.update({
  id: '/bulk_paste_filtering',
  path: '/bulk_paste_filtering',
  getParentRoute: () => rootRouteImport,
} as any)
const Bilaspur_diariesRoute = Bilaspur_diariesRouteImport.update({
  id: '/bilaspur_diaries',
  path: '/bilaspur_diaries',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bilaspur_diaries': typeof Bilaspur_diariesRoute
  '/bulk_paste_filtering': typeof Bulk_paste_filteringRoute
  '/cafes_human_behaviour': typeof Cafes_human_behaviourRoute
  '/career': typeof CareerRoute
  '/cohortup': typeof CohortupRoute
  '/employees_skin_in_the_game': typeof Employees_skin_in_the_gameRoute
  '/experiments': typeof ExperimentsRoute
  '/life': typeof LifeRoute
  '/online_writing': typeof Online_writingRoute
  '/phone_a_friend': typeof Phone_a_friendRoute
  '/phone_of_friend': typeof Phone_of_friendRoute
  '/recruiters_live_in_excel': typeof Recruiters_live_in_excelRoute
  '/reimagining_indian_agriculture': typeof Reimagining_indian_agricultureRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/theses': typeof ThesesRoute
  '/theses_and_experiments': typeof Theses_and_experimentsRoute
  '/ux_notes': typeof Ux_notesRoute
  '/work': typeof WorkRoute
  '/zunction': typeof ZunctionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bilaspur_diaries': typeof Bilaspur_diariesRoute
  '/bulk_paste_filtering': typeof Bulk_paste_filteringRoute
  '/cafes_human_behaviour': typeof Cafes_human_behaviourRoute
  '/career': typeof CareerRoute
  '/cohortup': typeof CohortupRoute
  '/employees_skin_in_the_game': typeof Employees_skin_in_the_gameRoute
  '/experiments': typeof ExperimentsRoute
  '/life': typeof LifeRoute
  '/online_writing': typeof Online_writingRoute
  '/phone_a_friend': typeof Phone_a_friendRoute
  '/phone_of_friend': typeof Phone_of_friendRoute
  '/recruiters_live_in_excel': typeof Recruiters_live_in_excelRoute
  '/reimagining_indian_agriculture': typeof Reimagining_indian_agricultureRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/theses': typeof ThesesRoute
  '/theses_and_experiments': typeof Theses_and_experimentsRoute
  '/ux_notes': typeof Ux_notesRoute
  '/work': typeof WorkRoute
  '/zunction': typeof ZunctionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bilaspur_diaries': typeof Bilaspur_diariesRoute
  '/bulk_paste_filtering': typeof Bulk_paste_filteringRoute
  '/cafes_human_behaviour': typeof Cafes_human_behaviourRoute
  '/career': typeof CareerRoute
  '/cohortup': typeof CohortupRoute
  '/employees_skin_in_the_game': typeof Employees_skin_in_the_gameRoute
  '/experiments': typeof ExperimentsRoute
  '/life': typeof LifeRoute
  '/online_writing': typeof Online_writingRoute
  '/phone_a_friend': typeof Phone_a_friendRoute
  '/phone_of_friend': typeof Phone_of_friendRoute
  '/recruiters_live_in_excel': typeof Recruiters_live_in_excelRoute
  '/reimagining_indian_agriculture': typeof Reimagining_indian_agricultureRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/theses': typeof ThesesRoute
  '/theses_and_experiments': typeof Theses_and_experimentsRoute
  '/ux_notes': typeof Ux_notesRoute
  '/work': typeof WorkRoute
  '/zunction': typeof ZunctionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/bilaspur_diaries'
    | '/bulk_paste_filtering'
    | '/cafes_human_behaviour'
    | '/career'
    | '/cohortup'
    | '/employees_skin_in_the_game'
    | '/experiments'
    | '/life'
    | '/online_writing'
    | '/phone_a_friend'
    | '/phone_of_friend'
    | '/recruiters_live_in_excel'
    | '/reimagining_indian_agriculture'
    | '/sitemap.xml'
    | '/theses'
    | '/theses_and_experiments'
    | '/ux_notes'
    | '/work'
    | '/zunction'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/bilaspur_diaries'
    | '/bulk_paste_filtering'
    | '/cafes_human_behaviour'
    | '/career'
    | '/cohortup'
    | '/employees_skin_in_the_game'
    | '/experiments'
    | '/life'
    | '/online_writing'
    | '/phone_a_friend'
    | '/phone_of_friend'
    | '/recruiters_live_in_excel'
    | '/reimagining_indian_agriculture'
    | '/sitemap.xml'
    | '/theses'
    | '/theses_and_experiments'
    | '/ux_notes'
    | '/work'
    | '/zunction'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/bilaspur_diaries'
    | '/bulk_paste_filtering'
    | '/cafes_human_behaviour'
    | '/career'
    | '/cohortup'
    | '/employees_skin_in_the_game'
    | '/experiments'
    | '/life'
    | '/online_writing'
    | '/phone_a_friend'
    | '/phone_of_friend'
    | '/recruiters_live_in_excel'
    | '/reimagining_indian_agriculture'
    | '/sitemap.xml'
    | '/theses'
    | '/theses_and_experiments'
    | '/ux_notes'
    | '/work'
    | '/zunction'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  Bilaspur_diariesRoute: typeof Bilaspur_diariesRoute
  Bulk_paste_filteringRoute: typeof Bulk_paste_filteringRoute
  Cafes_human_behaviourRoute: typeof Cafes_human_behaviourRoute
  CareerRoute: typeof CareerRoute
  CohortupRoute: typeof CohortupRoute
  Employees_skin_in_the_gameRoute: typeof Employees_skin_in_the_gameRoute
  ExperimentsRoute: typeof ExperimentsRoute
  LifeRoute: typeof LifeRoute
  Online_writingRoute: typeof Online_writingRoute
  Phone_a_friendRoute: typeof Phone_a_friendRoute
  Phone_of_friendRoute: typeof Phone_of_friendRoute
  Recruiters_live_in_excelRoute: typeof Recruiters_live_in_excelRoute
  Reimagining_indian_agricultureRoute: typeof Reimagining_indian_agricultureRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ThesesRoute: typeof ThesesRoute
  Theses_and_experimentsRoute: typeof Theses_and_experimentsRoute
  Ux_notesRoute: typeof Ux_notesRoute
  WorkRoute: typeof WorkRoute
  ZunctionRoute: typeof ZunctionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/zunction': {
      id: '/zunction'
      path: '/zunction'
      fullPath: '/zunction'
      preLoaderRoute: typeof ZunctionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work': {
      id: '/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof WorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ux_notes': {
      id: '/ux_notes'
      path: '/ux_notes'
      fullPath: '/ux_notes'
      preLoaderRoute: typeof Ux_notesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/theses_and_experiments': {
      id: '/theses_and_experiments'
      path: '/theses_and_experiments'
      fullPath: '/theses_and_experiments'
      preLoaderRoute: typeof Theses_and_experimentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/theses': {
      id: '/theses'
      path: '/theses'
      fullPath: '/theses'
      preLoaderRoute: typeof ThesesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reimagining_indian_agriculture': {
      id: '/reimagining_indian_agriculture'
      path: '/reimagining_indian_agriculture'
      fullPath: '/reimagining_indian_agriculture'
      preLoaderRoute: typeof Reimagining_indian_agricultureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruiters_live_in_excel': {
      id: '/recruiters_live_in_excel'
      path: '/recruiters_live_in_excel'
      fullPath: '/recruiters_live_in_excel'
      preLoaderRoute: typeof Recruiters_live_in_excelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/phone_of_friend': {
      id: '/phone_of_friend'
      path: '/phone_of_friend'
      fullPath: '/phone_of_friend'
      preLoaderRoute: typeof Phone_of_friendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/phone_a_friend': {
      id: '/phone_a_friend'
      path: '/phone_a_friend'
      fullPath: '/phone_a_friend'
      preLoaderRoute: typeof Phone_a_friendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/online_writing': {
      id: '/online_writing'
      path: '/online_writing'
      fullPath: '/online_writing'
      preLoaderRoute: typeof Online_writingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/life': {
      id: '/life'
      path: '/life'
      fullPath: '/life'
      preLoaderRoute: typeof LifeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiments': {
      id: '/experiments'
      path: '/experiments'
      fullPath: '/experiments'
      preLoaderRoute: typeof ExperimentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees_skin_in_the_game': {
      id: '/employees_skin_in_the_game'
      path: '/employees_skin_in_the_game'
      fullPath: '/employees_skin_in_the_game'
      preLoaderRoute: typeof Employees_skin_in_the_gameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cohortup': {
      id: '/cohortup'
      path: '/cohortup'
      fullPath: '/cohortup'
      preLoaderRoute: typeof CohortupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career': {
      id: '/career'
      path: '/career'
      fullPath: '/career'
      preLoaderRoute: typeof CareerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cafes_human_behaviour': {
      id: '/cafes_human_behaviour'
      path: '/cafes_human_behaviour'
      fullPath: '/cafes_human_behaviour'
      preLoaderRoute: typeof Cafes_human_behaviourRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bulk_paste_filtering': {
      id: '/bulk_paste_filtering'
      path: '/bulk_paste_filtering'
      fullPath: '/bulk_paste_filtering'
      preLoaderRoute: typeof Bulk_paste_filteringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bilaspur_diaries': {
      id: '/bilaspur_diaries'
      path: '/bilaspur_diaries'
      fullPath: '/bilaspur_diaries'
      preLoaderRoute: typeof Bilaspur_diariesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  Bilaspur_diariesRoute: Bilaspur_diariesRoute,
  Bulk_paste_filteringRoute: Bulk_paste_filteringRoute,
  Cafes_human_behaviourRoute: Cafes_human_behaviourRoute,
  CareerRoute: CareerRoute,
  CohortupRoute: CohortupRoute,
  Employees_skin_in_the_gameRoute: Employees_skin_in_the_gameRoute,
  ExperimentsRoute: ExperimentsRoute,
  LifeRoute: LifeRoute,
  Online_writingRoute: Online_writingRoute,
  Phone_a_friendRoute: Phone_a_friendRoute,
  Phone_of_friendRoute: Phone_of_friendRoute,
  Recruiters_live_in_excelRoute: Recruiters_live_in_excelRoute,
  Reimagining_indian_agricultureRoute: Reimagining_indian_agricultureRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ThesesRoute: ThesesRoute,
  Theses_and_experimentsRoute: Theses_and_experimentsRoute,
  Ux_notesRoute: Ux_notesRoute,
  WorkRoute: WorkRoute,
  ZunctionRoute: ZunctionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
